# hosts/example/default.nix
#
# A complete, commented host configuration. It doubles as reference
# documentation for every option that the agentic-nixos-integration
# modules introduce at the NixOS level (`systemApps.*`).
#
# The convention across this flake:
#
#   * Every installable app or service is a single module exposing one
#     toggle: `systemApps.<name>.enable = true;`.
#   * Modules may add extra options of their own — each one is shown
#     and explained below.
#   * You only ever set `.enable` and those extra options. Things like
#     `native`, `nativeConfig` or `packages` are parameters for module
#     authors (see lib/mkSystemApp.nix), not something a host touches.
#
# Per-user (home-manager) options live in users/example/ instead.

{ ... }:

{
  imports = [ ../../users/example ];

  # --- Housekeeping ---------------------------------------------------
  # The release this system was first installed from. Like
  # home.stateVersion (see users/example/home.nix) it must stay at its
  # initial value forever — it does NOT follow your nixpkgs channel.
  #
  # A real host also needs its disk layout and bootloader here, usually
  # via `imports = [ ./hardware-configuration.nix ];` generated by the
  # installer. The example omits it so it can be evaluated anywhere.
  system.stateVersion = "26.11";

  # ==================================================================
  # Ollama — local LLM inference server
  # ==================================================================
  # Enabling `systemApps.ollama` starts the ollama daemon (port 11434)
  # and registers a oneshot unit `ollama-pull-model.service` which, on
  # boot, pulls exactly one model from the ollama registry — or imports
  # it from a local file if you set `modelFile`. Everything else on the
  # system reads its model name from here, so this block is the single
  # source of truth for "which LLM does this machine use".
  systemApps.ollama = {
    enable = true;

    # --- GPU acceleration -------------------------------------------
    # Pick at most one; an assertion fails the build if both are set.
    # Leaving both false builds the plain CPU version.
    nvidia = false; # CUDA build (pkgs.ollama-cuda)
    amd = false;    # ROCm build (pkgs.ollama-rocm)

    # --- Model -------------------------------------------------------
    # Name used for the pull/import AND the name every consumer sees.
    # Must exist in the ollama registry unless you import it yourself
    # via `modelFile`. Change this one line to move the whole machine
    # onto a different model.
    model = "gemma4:12b";

    # --- Context window ----------------------------------------------
    # Sets OLLAMA_CONTEXT_LENGTH on the service. Ollama's built-in
    # default of 4096 tokens truncates agentic workloads (long system
    # prompts, tool outputs) and clients cannot override it per request,
    # so it has to be raised here. The KV cache grows linearly with
    # this value — raise only as far as your VRAM allows.
    contextLength = 32768;

    # --- Local model file (optional) ----------------------------------
    # Import a local .gguf instead of pulling from the registry. The
    # model is registered under the name in `model`, so consumers don't
    # need to know where it came from.
    #
    # Relative paths resolve against your flake source (the read-only
    # store copy); absolute paths are used in place. The service unit
    # automatically waits for the path's mount via RequiresMountsFor.
    #
    # modelFile = "/var/lib/models/gemma4-12b.gguf";
  };

  # ==================================================================
  # agentic-nix — natural-language control over this very machine
  # ==================================================================
  # Installs the `agentic-nix` CLI. Running `agentic-nix "<request>"`
  # pipes the request through opencode against your config repo, runs
  # `nixos-rebuild build`, and finally switches with nh.
  #
  # Options:
  #
  #   backend = "ollama" | "claude-api"   (default: "ollama")
  #
  # With "ollama" the CLI uses the local ollama service and the same
  # model configured above — no API key needed. Setting it here also
  # enables `systemApps.ollama` automatically, so you can omit that
  # block entirely if the defaults suit you.
  #
  # With "claude-api" opencode talks to Anthropic instead; pick this on
  # machines without a usable GPU. You will need credentials available
  # to opencode (e.g. an ANTHROPIC_API_KEY in your environment).
  systemApps.agentic-nix = {
    enable = true;
    backend = "ollama";
  };
}
